apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: develop-arc
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      enterprise: testing-devsecops
      group: develop-arc
      image: ghcr.io/actions/actions-runner:latest
      dockerdWithinRunnerContainer: true
      ephemeral: true
      resources:
        limits:
          cpu: "1500m"
          memory: "3Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"
