apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: rn-develop
  namespace: actions-runner-system
spec:
  replicas: 4
  template:
    spec:
      enterprise: "testing-devsecops"
      group: "develop-arc"
      image: ubuntu:22.04
      dockerdWithinRunnerContainer: true
      ephemeral: true
      resources:
        limits:
          cpu: "2.0"
          memory: "4Gi"
        requests:
          cpu: "1.0"
          memory: "2Gi"
