apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: rn-develop
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      enterprise: "Testing-DevSecOps"
      group: "gh-rn-develop"
      image: ghcr.io/actions/actions-runner:latest
      dockerdWithinRunnerContainer: true
      ephemeral: false
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "2Gi"

