# apiVersion: actions.summerwind.dev/v1alpha1
# kind: RunnerDeploymentRunner
# metadata:
#   name: rn-develop
#   namespace: actions-runner-system
# spec:
#   replicas: 1
#   template:
#     spec:
#       enterprise: "Testing-DevSecOps"
#       group: "gh-rn-develop"
#       image: ghcr.io/actions/actions-runner:latest
#       dockerdWithinRunnerContainer: true
#       ephemeral: true
#       resources:
#         limits:
#           cpu: "2"
#           memory: "4Gi"
#         requests:
#           cpu: "1"
#           memory: "2Gi"

apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: rn-develop
  namespace: actions-runner-system
spec:
  enterprise: "Testing-DevSecOps"  # o "organization" si aplica
  group: "gh-rn-develop"
  image: johanrn21/gh-runner-ubuntu:latest  # <-- Aquí usas tu imagen
  dockerdWithinRunnerContainer: true
  ephemeral: false
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "1"
      memory: "2Gi"

