apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: rn-develop
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      enterprise: "testing-devsecops"
      group: "develop-arc"
      image: ubuntu:22.04
      dockerdWithinRunnerContainer: true
      ephemeral: true
      resources:
        limits:
          cpu: "1.5"
          memory: "3Gi"
        requests:
          cpu: "0.5"
          memory: "1Gi"

