name: Deploy ARC and Runners

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create namespace for ARC
        run: |
          kubectl create namespace actions-runner-system --dry-run=client -o yaml | kubectl apply -f -

      - name: Add Helm repositories
        run: |
          helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
          helm repo add jetstack https://charts.jetstack.io
          helm repo update

      - name: Install cert-manager
        run: |
          kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --version v1.14.4 \
            --set installCRDs=true

      - name: Wait for cert-manager to be ready
        run: |
          kubectl rollout status deployment cert-manager -n cert-manager --timeout=120s

      - name: Install actions-runner-controller
        run: |
          helm upgrade --install arc actions-runner-controller/actions-runner-controller \
            --namespace actions-runner-system \
            --create-namespace \
            --set=authSecret.create=true \
            --set=authSecret.github_token=${{ secrets.GH_TOKEN_ARC }}
      - name: List repo files
        run: ls -la

      - name: Apply runner deployment
        run: |
          kubectl apply -f ./manifests/github-actions-runner-deployment.yml
