name: Deploy ARC and Runners

on:
  workflow_dispatch:
    inputs:
      log:
        description: "¿Ver logs después del despliegue?"
        required: false
        default: "false"

jobs:
  deploy:
    if: ${{ github.event.inputs.log != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Create ARC namespace
        run: |
          kubectl create namespace actions-runner-system --dry-run=client -o yaml | kubectl apply -f -

      - name: Install cert-manager
        run: |
          kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.2/cert-manager.crds.yaml
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version v1.14.2

      - name: Add ARC Helm repo
        run: |
          helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
          helm repo update

      - name: Install actions-runner-controller
        run: |
          helm upgrade --install arc actions-runner-controller/actions-runner-controller \
            --namespace actions-runner-system \
            --create-namespace \
            --set=authSecret.create=true \
            --set=authSecret.github_token=${{ secrets.GH_TOKEN_ARC }}

      - name: Wait for ARC webhook to be ready
        run: |
          echo "Waiting for ARC webhook to be ready..."
          kubectl rollout status deployment/arc-actions-runner-controller -n actions-runner-system --timeout=120s

      - name: Check ARC pods
        run: |
          kubectl get pods -n actions-runner-system

      - name: Apply runner deployment
        run: |
          kubectl apply -f ./manifests/github-actions-runner-deployment.yml

      - name: Esperar pod del runner y mostrar logs
        run: |
          echo "Esperando pod del runner..."
          for i in {1..12}; do
            pod=$(kubectl get pods -n actions-runner-system -l actions.github.com/runner-deployment-name=gh-rn-develop -o jsonpath="{.items[0].metadata.name}")
            if [ -n "$pod" ]; then
              echo "Runner pod encontrado: $pod"
              kubectl logs $pod -n actions-runner-system --tail=100
              exit 0
            fi
            echo "Intento $i: Pod aún no aparece, esperando 10s..."
            sleep 10
          done
          echo "No se encontró ningún pod del runner después de 2 minutos."
          exit 1

  show-logs:
    if: ${{ github.event.inputs.log == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Mostrar logs del ARC controller
        run: |
          echo "Mostrando pods del namespace actions-runner-system..."
          kubectl get pods -n actions-runner-system
          echo "------ Logs del ARC controller ------"
          pod=$(kubectl get pods -n actions-runner-system -l app.kubernetes.io/name=actions-runner-controller -o jsonpath="{.items[0].metadata.name}")
          if [ -n "$pod" ]; then
            kubectl logs $pod -n actions-runner-system --tail=100
          else
            echo "No se encontró el pod del ARC controller."
          fi

      - name: Mostrar logs del runner (si existe)
        run: |
          pod=$(kubectl get pods -n actions-runner-system -l actions.github.com/runner-deployment-name=gh-rn-develop -o jsonpath="{.items[0].metadata.name}")
          if [ -n "$pod" ]; then
            echo "------ Logs del runner: $pod ------"
            kubectl logs $pod -n actions-runner-system --tail=100
          else
            echo "No se encontró ningún pod del runner."
