name: Deploy ARC and Runners

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Create namespace
        run: |
          kubectl create namespace actions-runner-system --dry-run=client -o yaml | kubectl apply -f -

      - name: Add Helm repo
        run: |
          helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
          helm repo update

      - name: Install actions-runner-controller
        run: |
          helm upgrade --install arc actions-runner-controller/actions-runner-controller \
            --namespace actions-runner-system \
            --create-namespace \
            --set=authSecret.create=true \
            --set=authSecret.github_token=${{ secrets.GITHUB_TOKEN_ARC }}

      - name: Apply runner deployment
        run: |
          kubectl apply -f github-actions-runner-deployment.yml
